  
language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_KEY
  local_dir: build
  on:
    branch: master
notifications:
  webhooks:
    urls:
      - https://api.ghostinspector.com/v1/suites/5ea7eb74c4243452906711e7/execute/?apiKey=edfe23ab5d4550d8ce824da111fee9ef87ad21fe
    on_success: always
    on_failure: never