language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_KEY
  local_dir: build
  on:
    branch: master
   after_success: |
  if [ -n "$GITHUB_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    # This generates a `web` directory containing the website.
    make web
    cd web
    git init
    git checkout -b gh-pages
    git add .
    git -c user.name='Matasj98' -c user.email='jari.matas@gmail.com' commit -m init
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your passwrd.
    git push -f -q https://Matasj98:$GITHUB_KEY@github.com/Matasj98/Plack-gh-pages gh-pages &>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi